server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001              #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service           #写微服务的名字，不能写死
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2024-03-17T12:45:32.849136+08:00[GMT+08:00]
            # - Between=2024-03-17T12:45:32.849136+08:00[GMT+08:00], 2024-03-17T12:48:32.849136+08:00[GMT+08:00]
            # - Before=2024-03-17T12:49:32.849136+08:00[GMT+08:00]
            # - Cookie=username,srb
            # - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            # - Host=**.atguigu.com
            # - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
            # - RemoteAddr=0.0.0.0/0 # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
            # - Method=GET,POST
            # - My=fuck

        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001              #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service           #写微服务的名字，不能写死
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
            # - Path=/gateway/filter/**                    # 断言，路径相匹配的进行路由
            # - Path=/XYZ/abc/{segment}  # 访问路径 http://localhost:9527/XYZ/abc/filter
          filters:
            # - SetPath=/pay/gateway/{segment}  # 修改访问路径实际  http://localhost:pay/gateway/filter
            # - RedirectTo=302,https://www.baidu.com
            # - PrefixPath=/pay  # 自动拼接前面的路径
            # - AddRequestHeader=X-Request-srb1,srbValue1  # 请求头kv，若一头含有多参则重写一行设置
            # - AddRequestHeader=X-Request-srb2,srbValue2
            # - RemoveRequestHeader=sec-fetch-site  # 根据请求头的名字，删除掉该请求头信息
            # - SetRequestHeader=sec-fetch-mode,fucYou  # 根据请求头名字，修改请求头的值
            # - AddRequestParameter=username,zhangsan  # 新增请求参数Parameter: key, value
            # - RemoveRequestParameter=password  # 删除请求参数，如果传递，也是null
            # - AddResponseHeader=fuck,loveYou  # 新增响应参数
            # - SetResponseHeader=Date,2099-12-31  # 设置响应头Date的值
            # - RemoveResponseHeader=Content-Type  # 删除响应头名为Content-Type的数据
            - My=fuck