USE dbtest1;

# 使用myisam存储引擎创建一个表
CREATE TABLE `student_myisam`(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) DEFAULT NULL,
	`age` INT DEFAULT NULL,
	`sex` VARCHAR(2) DEFAULT NULL,
	PRIMARY KEY(`id`)
)ENGINE = MYISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb3;

