/**
 * @author ShiRongbao
 * @create 2024/11/8
 * @description:
 */
public class test {

    public static void main(String[] args) {
        String str = "{\"oneSentenceSummary\":\"阳光帅气的理工男，正经历大学初恋的情感挑战。\",\"basicInformation\":{\"name\":\"李楠\",\"gender\":\"男\",\"age\":\"19\",\"currentCity\":\"上海\",\"hometownCity\":\"南京\",\"occupationOrSchool\":\"上海科技大学\"},\"lifeBackground\":{\"familySituation\":\"李楠的家庭和睦，父母是普通公务员，有一个小自己两岁的妹妹。\",\"maritalStatus\":\"单身\",\"children\":\"无\",\"childhoodExperiences\":\"在父母的陪伴和支持下成长，性格开朗，童年充满了爱和安全感。\",\"culturalValues\":\"注重努力与成绩，对未来有追求新知和自我实现的价值观。\"},\"careerAndEducationalBackground\":{\"educationalBackground\":\"成绩优异，从小学到高中一直是学术霸主，现在是计算机科学与技术专业的学生。\",\"careerBackground\":\"暂无职业经历，正在逐步接触学术研究与项目实习。\"},\"currentTroubles\":{\"coreIssue\":\"对班上一位女生的单相思。\",\"emotionalDistress\":\"对女生不回应他心意的失落和疑虑。\",\"mainConflicts\":\"继续追求与放弃的内心矛盾。\",\"mentalState\":\"总体积极，但情感上有些困惑和失落。\"},\"impactOfTroubles\":{\"behavior\":\"在女生面前会显得有些紧张，可能会更努力参与学习和活动以展示自己。\",\"cognition\":\"对追求此感情关系的可行性有过度分析和忧虑。\",\"emotion\":\"情绪有时波动，虽然常保持快乐的外表，但内心对未来有些焦虑。\",\"interpersonalRelationships\":\"在其他人面前仍旧活跃，但对女生显得有点腼腆且小心翼翼。\",\"personalityTraits\":\"开朗，积极，求知欲强，但感情方面略显不自信。\"},\"positiveAttempts\":{\"pastCoping\":\"通过写代码和锻炼来转移注意力，尝试结交新朋友。\",\"strategySummary\":\"以活动和兴趣分散注意力，同时努力改善社交技巧。\"},\"supportResources\":{\"emotionalSupport\":\"得到了家人和几位老朋友的倾听与开导。\",\"socialSupport\":\"班级和宿舍的同学关系融洽，能给予一定的支持和建议。\",\"economicSupport\":\"家庭经济条件良好，生活条件稳定。\",\"professionalSupport\":\"导师和学长学姐提供学业和职业指导。\"},\"consultationGoalsAndExpectations\":\"希望能理清自己的感情选择及自信心不足的问题，改善与女生的互动。\",\"detailedLifeEventStory\":[\"李楠小时候非常喜欢和父母一起去附近的公园玩耍。每到周末，他都会跟着爸爸妈妈骑自行车到公园观鸟。他尤其喜欢雀鸟，因为它们总是能给他带来新的发现。这些温馨的家庭时光让他拥有了一个平静而幸福的童年，也塑造了他喜爱大自然，及生活中小事的重要价值观。\",\"高三那年，李楠在省级科学创新竞赛上获得一等奖，令他倍感自豪和鼓励。他为了这个项目连续三个星期熬夜，最终在老师和同学的支持下成功地完成了。这段经历不仅提升了他的自信心，也坚定了他对计算机技术的热爱与追求。\",\"进入大学后，李楠迅速融入了计算机科学与技术系的生活。他加入了编程社团并积极参加各类技术项目，希望通过这些活动扩展自己的专业技能。然而，他也意识到自己在社交方面有待提高，因此努力鼓励自己更多参与校内社交活动。\",\"最近，李楠注意到班上一位特别的女生，她与他有相似的爱好和志向。在一次学术交流会上，他主动上前与她交谈，发现两人有很多共同话题。这次交流让他对女生产生了更深的好感，同时也增添了他对未来关系发展的期待。\",\"然而，随着时间推移，李楠发现女生对他没有特别的回应。这使他一次次感到困惑和失落。他尝试通过各种方式吸引她的注意，但始终得不到期望的回应。面对这样的一份单恋，他不知是否继续坚持，更难在这段感情中找到方向。\"],\"languageStyle\":{\"expressionStyle\":\"表达通常直接却偶尔犹豫，语句结构较为复杂。\",\"tone\":\"语气有时流露出焦虑，但多数情况下保持平和。\",\"wordChoice\":\"使用积极且富有探索性的词汇，间或流露出犹疑。\",\"emotionalIntensity\":\"情感表达时而强烈，尤其提到感情问题时。\",\"logicAndOrganization\":\"逻辑性较强，条理清晰，但情感问题上会显得困惑。\",\"speechRateAndPauses\":\"说话较快，但在感情话题上容易停顿。\"}}";
    }
}
