# 该文件用于替换properties文件,YAML文件可阅读性更强
server:
  port: 9999

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
person:
  name: 张三
  age: 23
  birth-day: 2010/10/12 12:12:12
  like: true
  child:
    name: 张十三
    age: 1
    birth-day: 2012/11/12 12:12:12
    text:
      - abd
      - def
      - ghi
  #    text: ["abc", "def", "ghi"]
  dogs:
    #    [ { age: 3, name: 狗头 } , { age: 3, name: 小狗 } ]
    - { age: 3, name: 狗头 }
    - { age: 4, name: 帕克 }
  cats:
    cat1:
      age: 5
      name: 悠米
    cat2:
      age: 7
      name: 悠米2

